fix: None values handling in array type details
Filter out None values from details when joining.

This solves the case when you have the data:
```
"anyOf": [
  { "required": ["A"] },
  { "required": ["B"] }
]
```
Which otherwise gives this error:
```
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```